export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const RETRIEVE_CART = "RETRIEVE_CART";
export const SET_CART = "SET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_CHECKOUT_TOKEN = "SET_CHECKOUT_TOKEN";
